# Generated by Django 4.2.2 on 2023-06-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_classroom_desc_subject_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='week',
        ),
    ]
