# Generated by Django 4.2.2 on 2023-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_timetable_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
