# Generated by Django 4.2.2 on 2023-06-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_timetable_end_date_timetable_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='teach_by',
            new_name='teacher',
        ),
    ]
