# Generated by Django 4.2.2 on 2023-06-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_teach_by_timetable_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='level',
        ),
    ]
