# Generated by Django 4.2.2 on 2023-06-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_timetable_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bgColor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
