# Generated by Django 4.2.2 on 2023-06-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
