# Generated by Django 4.2.2 on 2023-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_notification_is_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_opened',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
