# Generated by Django 4.2.2 on 2023-06-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_chat_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_by',
            new_name='user',
        ),
    ]
