# Generated by Django 4.2.2 on 2023-06-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_chat_options_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='elt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
