# Generated by Django 4.2.2 on 2023-06-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_myuser_created_by_myuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
