# Generated by Django 4.2.2 on 2023-06-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_myuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
