# Generated by Django 4.2.2 on 2023-06-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_level_total_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.level'),
        ),
    ]
