# Generated by Django 4.2.2 on 2023-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_alter_myuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
